services:
  db:
    image: postgres:16-alpine
    container_name: pbms-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pbms_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password_here
    tmpfs:
      - /var/lib/postgresql/data
